Homework 2 completed
aikido-sensei/pyWiki pull request #2
Opened 2021-09-10 00:22 UTC by aikido-sensei

2021-09-10 00:25 UTC, the-c0d3br34k3r commented on wiki/conditions/logical_operators.py
> +#this "or" evaluates both condition even if the firs is true
*first.

2021-09-10 00:27 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +        self.speed_in_kmph: float = 0
Please revert the variables to private form.

2021-09-10 00:29 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +            desired_speed = 0
In such scenarios, throw an error.

2021-09-10 00:33 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +        Desired_speed: Is the speed at which you want the car to be.
Please fix documentation comments.

2021-09-10 00:39 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +
```suggestion
        time.sleep((self.speed_in_kmph - desired_speed)/5)
        self.speed_in_kmph = desired_speed
```

2021-09-10 00:42 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +              break
```suggestion
        time.sleep(time)
        self.speed_in_kmph = max(self.speed_in_kmph - time * 5, 0)
```

2021-09-10 00:43 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +    def brake_for(self, time: int ) -> None:
```suggestion
    def brake_for(self, time_in_seconds: int ) -> None:
```

2021-09-10 00:48 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +              break
```suggestion
        for second in range(time): 
          time.sleep(1)
          if self.speed_in_kmph > 1:
             self.speed_in_kmph = max(self.speed_in_kmph - 5, 0)
             
             
              self.speed_in_kmph -= 5
              time.sleep(0.9999999999)
        
          else:
              self.speed_in_kmph = 0
              time.sleep(0.9999999)
              break
```

2021-09-10 00:49 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +
Can you please add sample code for braking?

2021-09-10 00:49 UTC, the-c0d3br34k3r commented on wiki/general/lambdas.py
> +"""
TODO

2021-09-10 00:49 UTC, the-c0d3br34k3r commented on wiki/loops/recursion.py
> +"""
TODO

2021-09-10 00:55 UTC, the-c0d3br34k3r requested changes
Please address the requested changes.

2021-09-17 00:08 UTC, aikido-sensei commented on wiki/loops/recursion.py
> +"""
Adressed in #3

2021-09-17 00:09 UTC, aikido-sensei commented on wiki/general/lambdas.py
> +"""
Adressed in #3

2021-09-17 00:10 UTC, the-c0d3br34k3r approved these changes

2021-09-17 00:11 UTC, the-c0d3br34k3r requested changes
Please rebase the branch with main.

2021-09-17 14:52 UTC, the-c0d3br34k3r commented on wiki/general/classes.py
> +        self.speed_in_kmph: float = 0
Retain the variables as private.

2021-09-17 14:53 UTC, the-c0d3br34k3r requested changes
Requested changes and please rebase with the upstream main branch as well.

2021-09-22 00:21 UTC, the-c0d3br34k3r approved these changes

2021-09-22 00:21 UTC, merged